Login and Navbar
toggle-corp/ai-chatbot-cms pull request #10
Opened 2024-11-06 11:26 UTC by shreeyash07

- Add toggle-ui and toggle-form
- Add Auth wrapper
- Update routes functions

2025-02-05 05:37 UTC, barshathakuri requested changes

2025-02-05 05:37 UTC, barshathakuri commented on src/components/Navbar/index.tsx
> +    }, [logout]);
Use logout directly.

2025-02-05 05:37 UTC, barshathakuri commented on src/components/Navbar/styles.module.css
> +    box-shadow: 0px 4px 4px 0px rgba(227, 227, 227, 0.25);
```suggestion
    box-shadow: 0px 4px 4px 0px rgba(227, 227, 227, 0.25);
```
Why there is no token for box shadow?

2025-02-05 05:37 UTC, barshathakuri commented on src/components/Page/styles.module.css
> +        box-shadow: 0px 4px 4px 0px rgba(227, 227, 227, 0.25);
```suggestion
        box-shadow: 0px 4px 4px 0px rgba(227, 227, 227, 0.25);
```
Add design token here.

2025-02-05 05:37 UTC, barshathakuri commented on src/views/ContentManagement/index.tsx
> +    const handleActivePageChange = useCallback((e: number) => {
We can use setPage directly.

2025-02-05 05:49 UTC, samshara requested changes

2025-02-05 05:49 UTC, samshara commented on src/App/routes/index.tsx
> +    forwardPath: 'contentManagement',
```suggestion
    forwardPath: 'content-management',
```

2025-02-05 05:49 UTC, samshara commented on src/hooks/useAuth.ts
> +
This doesn't look correct

2025-02-05 05:49 UTC, samshara commented on src/index.css
> +
We should make this CSS variable name more descriptive.

2025-02-05 05:49 UTC, samshara commented on src/views/ContentManagement/index.tsx
> +    }, []);
Do we need this handler? Couldn't we use the setter function itself?

2025-02-05 05:49 UTC, samshara commented on src/views/ContentManagement/index.tsx
> +                </Button>
Button without `onClick` ?

2025-02-05 05:49 UTC, samshara commented on src/views/Login/index.tsx
> +                lengthGreaterThanCondition(1),
Let's add this in the condition itself.

2025-02-06 04:13 UTC, shreeyash07 commented on src/components/Navbar/styles.module.css
> +    box-shadow: 0px 4px 4px 0px rgba(227, 227, 227, 0.25);
still need to finalize the token with the design team

2025-02-06 04:13 UTC, shreeyash07 commented on src/components/Page/styles.module.css
> +        box-shadow: 0px 4px 4px 0px rgba(227, 227, 227, 0.25);
still need to finalize the token with the design team

2025-02-13 06:22 UTC, samshara approved these changes

2025-02-13 06:49 UTC, barshathakuri approved these changes

2025-02-13 06:49 UTC, merged